version: '3.3'
networks:
  project_net:
    driver: bridge
services:
    php:
      image: registry.cn-hangzhou.aliyuncs.com/guanfang/php:8.3-fpm
      ports:
        - "9501:9501"
        - "9502:9502"
        - "9503:9503"
        - "9504:9504"
        - "9505:9505"
        - "9506:9506"
      expose:
        - "9000"
      environment:
        TZ: Asia/Shanghai
        LC_ALL: C.UTF-8
      volumes:
        - ./www/:/www/:rw
        - ./conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
        - ./log/php-fpm/:/var/log/php-fpm/:rw
      networks:
        - "project_net"
        
    nginx:
      image: registry.cn-hangzhou.aliyuncs.com/guanfang/nginx:1.27.0
      ports:
        - "80:80"
        - "8000:8000"
        - "8080:8080"
        - "8081:8081"
        - "8088:8088"
        - "8888:8888"
        - "443:443"
      volumes:
        - ./www/:/www/:rw
        - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
        - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./log/nginx/:/var/log/nginx/:rw
      networks:
        - "project_net"
      environment:
        TZ: Asia/Shanghai
      links:
        - php:fpm
      
    mysql:
      image: registry.cn-hangzhou.aliyuncs.com/guanfang/mysql:5.7
      restart: always
      command:
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_general_ci
        --explicit_defaults_for_timestamp=true
        --lower_case_table_names=1
        --max_allowed_packet=128M
        --default-authentication-plugin=mysql_native_password
        --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"
      ports:
        - "3306:3306"
      volumes:
        - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
        - ./data/mysql/:/var/lib/mysql/:rw
        - ./log/mysql/:/var/log/mysql/:rw
      environment:
        MYSQL_ROOT_PASSWORD : 123456
        #MYSQL_DATABASE: blog
        TZ: Asia/Shanghai
      networks:
        - "project_net"
        
    redis:
      image: registry.cn-hangzhou.aliyuncs.com/guanfang/redis:6.0
      restart: always
      command: redis-server --requirepass 123456
      ports:
        - "6379:6379"
      networks:
        - "project_net"
        
    mongodb:
      image: registry.cn-hangzhou.aliyuncs.com/guanfang/mongo:7.0.12
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: 123456
      ports:
        - "27017:27017"
      volumes:
        - ./data/mongodb/:/data/db/:rw
      networks:
        - "project_net"
