version: '3.3'
services:
    php:
      image: laisxn/php:7.2-fpm
      ports:
        - "9501:9501"
        - "9502:9502"
        - "9503:9503"
      expose:
        - "9000"
      volumes:
        - ./www/:/www/:rw
        - ./conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
        - ./log/php-fpm/:/var/log/php-fpm/:rw
      networks:
        - project_net
        
    nginx:
      image: nginx:alpine
      ports:
        - "80:80"
        - "8080:8080"
        - "443:443"
      volumes:
        - ./www/:/www/:rw
        - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
        - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./log/nginx/:/var/log/nginx/:rw
      networks:
        - project_net
      #links:
      #  - php:fpm
      
    mysql:
      image: mysql:5.7
      ports:
        - "3306:3306"
      volumes:
        - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
        - ./data/mysql/:/var/lib/mysql/:rw
        - ./log/mysql/:/var/log/mysql/:rw
      environment:
        MYSQL_ROOT_PASSWORD : 123456
      networks:
        - project_net
        
    redis:
      image: redis:4.0
      restart: always
      command: redis-server --requirepass 123456
      ports:
        - "6379:6379"
      networks:
        - project_net
        
    mongodb:
      image: mongo:latest
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: 123456
      ports:
        - "27017:27017"
      volumes:
        - ./data/mongodb/:/data/db/:rw
        networks:
        - project_net
